version: 2.1

jobs:
  build:
    docker:
      - image: klakegg/hugo:ext-alpine
    working_directory: ~/my-app
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:p9wwvHNF/oqpSrJRYg0Yh4vuP3/iGo1aXmxaNmvbCrA vzvu3k6k@gmail.com"
      - checkout
      - run:
          name: Install third-party dependencies
          command: git submodule sync && git submodule update --init
      - run:
          name: Build Hugo Website
          command: hugo -v
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    docker:
      - image: cimg/node:lts
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "SHA256:p9wwvHNF/oqpSrJRYg0Yh4vuP3/iGo1aXmxaNmvbCrA vzvu3k6k@gmail.com"
      - run:
          name: Deploy to GitHub Pages
          command: |
            # Fix for https://github.com/tschaub/gh-pages/issues/354#issuecomment-674552919
            touch package.json

            npx gh-pages@3.2.3 \
              --dist public \
              --user "gocon-bot <gocon-bot@users.noreply.github.com>"
          working_directory: project

workflows:
  version: 2

  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main